# Generated by Django 5.0.6 on 2024-06-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_newusers_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='newusers',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newusers',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newusers',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newusers',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
